env:
 - GHCVER=7.0.4
 - GHCVER=7.2.2
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.3
 - GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update -qq
 - sudo apt-get install -qq cabal-install-1.18 ghc-$GHCVER
 - export PATH="/opt/ghc/$GHCVER/bin:$PATH"

install:
 - cabal-1.18 update
 - ghc --version
 - ghc-pkg list

script:
 - ls -l
 - cabal-1.18 install --enable-documentation
 - ls -l
 - ls -l dist
 - cabal-1.18 sdist --verbose=3
 - ls -l dist
 - wc dist/setup-config
 - ghc-pkg list
